name: Publish Preview

on:
  pull_request:

jobs:
  vercel_preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Raven certificate
        run: |
          mkdir certs
          echo '${{ secrets.RAVENDB_CERT }}' | base64 -d > ./certs/ravendb.pfx

      - name: Deploy to Vercel
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

        run: |
          npm i vercel -g
          mkdir .vercel
          echo {} | jq --arg "$VERCEL_ORG_ID" $org --arg projectId "$VERCEL_PROJECT_ID" '.={$orgId, $projectId}' > .vercel/project.json
          vercel --token $VERCEL_TOKEN
